import { Alumno, Profesor, Clase, PreguntaExamen, Logro } from './types'

// Alumno demo
export const alumnoDemo: Alumno = {
  id: '1',
  email: 'valentina.rodriguez@email.com',
  nombre: 'Valentina Rodríguez',
  sede: 'Rafaela, Santa Fe',
  turno: 'sábados',
  role: 'alumno',
  progreso: 7,
  asistencia: 82,
  examenEstado: 'pendiente',
  certificadoEmitido: false,
  rachaAsistencia: 4,
  promedioEjercicios: 78,
  createdAt: new Date('2026-02-01'),
}

// Profesor demo
export const profesorDemo: Profesor = {
  id: '2',
  email: 'marcos.gimenez@itcargentina.com',
  nombre: 'Lic. Marcos Giménez',
  sede: 'Rafaela, Santa Fe',
  turno: 'sábados',
  role: 'profesor',
  alumnosACargo: 18,
  createdAt: new Date('2024-01-15'),
}

// Lista de alumnos del grupo
export const alumnosDemo: Alumno[] = [
  alumnoDemo,
  {
    id: '3',
    email: 'juan.herrera@email.com',
    nombre: 'Juan Herrera',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 100,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 7,
    promedioEjercicios: 92,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '4',
    email: 'marta.giordano@email.com',
    nombre: 'Marta Giordano',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 6,
    asistencia: 73,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 2,
    promedioEjercicios: 65,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '5',
    email: 'santiago.lopez@email.com',
    nombre: 'Santiago López',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 4,
    asistencia: 45,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 0,
    promedioEjercicios: 42,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '6',
    email: 'lucia.pereyra@email.com',
    nombre: 'Lucía Pereyra',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 91,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 5,
    promedioEjercicios: 88,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '7',
    email: 'carlos.mendez@email.com',
    nombre: 'Carlos Méndez',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 86,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 3,
    promedioEjercicios: 75,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '8',
    email: 'ana.martinez@email.com',
    nombre: 'Ana Martínez',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 5,
    asistencia: 64,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 1,
    promedioEjercicios: 58,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '9',
    email: 'pedro.sanchez@email.com',
    nombre: 'Pedro Sánchez',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 95,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 6,
    promedioEjercicios: 82,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '10',
    email: 'maria.fernandez@email.com',
    nombre: 'María Fernández',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 6,
    asistencia: 77,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 2,
    promedioEjercicios: 70,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '11',
    email: 'diego.ruiz@email.com',
    nombre: 'Diego Ruiz',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 100,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 7,
    promedioEjercicios: 95,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '12',
    email: 'laura.gomez@email.com',
    nombre: 'Laura Gómez',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 3,
    asistencia: 36,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 0,
    promedioEjercicios: 35,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '13',
    email: 'roberto.silva@email.com',
    nombre: 'Roberto Silva',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 82,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 3,
    promedioEjercicios: 73,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '14',
    email: 'carolina.paz@email.com',
    nombre: 'Carolina Paz',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 91,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 4,
    promedioEjercicios: 85,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '15',
    email: 'fernando.castro@email.com',
    nombre: 'Fernando Castro',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 6,
    asistencia: 68,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 1,
    promedioEjercicios: 62,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '16',
    email: 'gabriela.torres@email.com',
    nombre: 'Gabriela Torres',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 86,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 4,
    promedioEjercicios: 79,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '17',
    email: 'martin.diaz@email.com',
    nombre: 'Martín Díaz',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 5,
    asistencia: 59,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 0,
    promedioEjercicios: 55,
    createdAt: new Date('2026-02-01'),
  },
  {
    id: '18',
    email: 'sofia.moreno@email.com',
    nombre: 'Sofía Moreno',
    sede: 'Rafaela, Santa Fe',
    turno: 'sábados',
    role: 'alumno',
    progreso: 7,
    asistencia: 95,
    examenEstado: 'pendiente',
    certificadoEmitido: false,
    rachaAsistencia: 5,
    promedioEjercicios: 90,
    createdAt: new Date('2026-02-01'),
  },
]

// Clases del curso (datos estáticos - el estado dinámico viene de la BD)
export const clasesDemo: Clase[] = [
  // Fase 1 - IA Aplicada (15 clases)
  { id: 1, numero: 1, titulo: 'La IA en tu vida diaria', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_01_IA_En_Tu_Vida.html' },
  { id: 2, numero: 2, titulo: 'Prompt Engineering: Fundamentos', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_02_Prompt_Engineering.html' },
  { id: 3, numero: 3, titulo: 'IA para Ventas y Atención al Cliente', categoria: 'ia-aplicada', categoriaLabel: 'Aplicación Comercial', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_03_IA_Ventas_Atencion_Cliente.html' },
  { id: 4, numero: 4, titulo: 'Copywriting y Contenido con IA', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_04_Copywriting_Contenido.html' },
  { id: 5, numero: 5, titulo: 'Diseño Visual e Imágenes con IA', categoria: 'diseno-ia', categoriaLabel: 'Diseño con IA', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_05_Diseno_Visual_Imagenes.html' },
  { id: 6, numero: 6, titulo: 'Canva: Flyers, Logos y Diseño', categoria: 'diseno-ia', categoriaLabel: 'Diseño con IA', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_06_Canva_Flyers_Logos.html' },
  { id: 7, numero: 7, titulo: 'Video y Marketing con IA', categoria: 'diseno-ia', categoriaLabel: 'Diseño con IA', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_07_Video_Marketing.html' },
  { id: 8, numero: 8, titulo: 'Productividad con IA', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_08_Productividad.html' },
  { id: 9, numero: 9, titulo: 'Análisis de Clientes y Mercado', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_09_Analisis_Clientes_Mercado.html' },
  { id: 10, numero: 10, titulo: 'Datos, Reportes y Excel con IA', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_10_Datos_Reportes_Excel.html' },
  { id: 11, numero: 11, titulo: 'GPT Personalizado para tu Negocio', categoria: 'estrategia', categoriaLabel: 'Estrategia', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_11_GPT_Personalizado.html' },
  { id: 12, numero: 12, titulo: 'Finanzas para PyME con IA', categoria: 'estrategia', categoriaLabel: 'Estrategia', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_12_Finanzas_Pyme.html' },
  { id: 13, numero: 13, titulo: 'Repaso Fase 1: IA Aplicada', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_13_Repaso_Fase1.html' },
  { id: 14, numero: 14, titulo: 'Agentes de IA y Futuro del Trabajo', categoria: 'ia-aplicada', categoriaLabel: 'IA Aplicada', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_14_Agentes_IA_Futuro_Trabajo.html' },
  { id: 15, numero: 15, titulo: 'Mini Proyecto I', categoria: 'proyectos', categoriaLabel: 'Proyectos', fase: 1, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_15_Mini_Proyecto_I.html' },

  // Fase 2 - Automatización (7 clases)
  { id: 16, numero: 16, titulo: 'Introducción a la Automatización', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_16_Introduccion_Automatizacion.html' },
  { id: 17, numero: 17, titulo: 'Conexiones en Make', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_17_Conexiones_Make.html' },
  { id: 18, numero: 18, titulo: 'APIs y JSON', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_18_APIs_JSON.html' },
  { id: 19, numero: 19, titulo: 'Automatización de WhatsApp', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_19_Automatizacion_WhatsApp.html' },
  { id: 20, numero: 20, titulo: 'Integración IA + Make', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_20_Integracion_IA_Make.html' },
  { id: 21, numero: 21, titulo: 'Filtros y Manejo de Errores', categoria: 'automatizacion', categoriaLabel: 'Automatización', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_21_Filtros_Errores.html' },
  { id: 22, numero: 22, titulo: 'Proyecto Final', categoria: 'proyectos', categoriaLabel: 'Proyectos', fase: 2, duracion: 90, estado: 'bloqueada', htmlPath: '/clases/Clase_22_Proyecto_Final.html' },
]

// Preguntas del examen (30 preguntas)
export const preguntasExamen: PreguntaExamen[] = [
  { id: 1, enunciado: '¿Qué es un "prompt" en el contexto de la IA?', opciones: { a: 'Un tipo de hardware especial', b: 'Las instrucciones que le das a una IA para obtener un resultado', c: 'Un virus informático', d: 'Una marca de software' }, respuestaCorrecta: 'b', claseRelacionada: 2 },
  { id: 2, enunciado: '¿Cuál de estas herramientas sirve para automatizar flujos entre aplicaciones SIN programar?', opciones: { a: 'Microsoft Word', b: 'Photoshop', c: 'Make (Integromat)', d: 'Excel' }, respuestaCorrecta: 'c', claseRelacionada: 16 },
  { id: 3, enunciado: 'En la analogía del temario, una API es como:', opciones: { a: 'El cocinero de un restaurante', b: 'El menú del restaurante: pedís algo y te lo traen', c: 'La caja registradora', d: 'El local físico' }, respuestaCorrecta: 'b', claseRelacionada: 17 },
  { id: 4, enunciado: '¿Qué significa "trigger" en Make?', opciones: { a: 'Un botón de eliminar', b: 'Un tipo de error del sistema', c: 'El evento que dispara o inicia una automatización', d: 'La pantalla de inicio' }, respuestaCorrecta: 'c', claseRelacionada: 16 },
  { id: 5, enunciado: '¿Cuál es el objetivo principal del "Prompt Engineering"?', opciones: { a: 'Programar apps desde cero', b: 'Estructurar instrucciones claras para obtener mejores resultados de la IA', c: 'Diseñar logos con inteligencia artificial', d: 'Configurar redes WiFi' }, respuestaCorrecta: 'b', claseRelacionada: 2 },
  { id: 6, enunciado: '¿Qué es un GPT personalizado?', opciones: { a: 'Una red de computadoras', b: 'Un modelo entrenado con datos específicos de tu negocio', c: 'Un tipo de virus', d: 'Una app de diseño' }, respuestaCorrecta: 'b', claseRelacionada: 5 },
  { id: 7, enunciado: '¿Qué formato usa Make para pasar datos entre módulos?', opciones: { a: 'DOC', b: 'MP4', c: 'JSON', d: 'ZIP' }, respuestaCorrecta: 'c', claseRelacionada: 18 },
  { id: 8, enunciado: 'ChatGPT fue creado por:', opciones: { a: 'Google', b: 'Microsoft', c: 'Apple', d: 'OpenAI' }, respuestaCorrecta: 'd', claseRelacionada: 4 },
  { id: 9, enunciado: '¿Qué hace el módulo "Iterator" en Make?', opciones: { a: 'Crea PDFs', b: 'Envía emails', c: 'Separa elementos de una lista para procesarlos uno a uno', d: 'Genera imágenes' }, respuestaCorrecta: 'c', claseRelacionada: 18 },
  { id: 10, enunciado: '¿Qué significa ROI?', opciones: { a: 'Tipo de software', b: 'Retorno de la inversión', c: 'Red de internet', d: 'Registro de operaciones' }, respuestaCorrecta: 'b', claseRelacionada: 13 },
  { id: 11, enunciado: '¿Cuál es la función de Canva en el curso?', opciones: { a: 'Automatización', b: 'Diseño gráfico con asistencia de IA', c: 'Análisis de datos', d: 'Atención al cliente' }, respuestaCorrecta: 'b', claseRelacionada: 6 },
  { id: 12, enunciado: 'El framework RTF para prompts significa:', opciones: { a: 'Red, Token, Formato', b: 'Rol, Tarea, Formato', c: 'Resultado, Tiempo, Función', d: 'Registro, Tono, Fondo' }, respuestaCorrecta: 'b', claseRelacionada: 2 },
  { id: 13, enunciado: '¿Para qué sirve Remove.bg?', opciones: { a: 'Crear videos', b: 'Eliminar fondos de imágenes', c: 'Escribir emails', d: 'Hacer presentaciones' }, respuestaCorrecta: 'b', claseRelacionada: 7 },
  { id: 14, enunciado: '¿Qué herramienta se recomienda para edición de video con IA?', opciones: { a: 'Photoshop', b: 'Word', c: 'CapCut', d: 'Google Maps' }, respuestaCorrecta: 'c', claseRelacionada: 8 },
  { id: 15, enunciado: 'Un "buyer persona" es:', opciones: { a: 'Un tipo de anuncio', b: 'El perfil ideal del cliente', c: 'Una herramienta de IA', d: 'Un formato de imagen' }, respuestaCorrecta: 'b', claseRelacionada: 14 },
  { id: 16, enunciado: '¿Qué es Make (Integromat)?', opciones: { a: 'Red social', b: 'Motor de búsqueda', c: 'Plataforma de automatización sin código', d: 'Herramienta de diseño' }, respuestaCorrecta: 'c', claseRelacionada: 16 },
  { id: 17, enunciado: '¿Cuántas apps conecta Make aproximadamente?', opciones: { a: '10', b: '150', c: '1.500+', d: '50' }, respuestaCorrecta: 'c', claseRelacionada: 16 },
  { id: 18, enunciado: 'En Make, ¿qué es un "escenario"?', opciones: { a: 'Imagen de fondo', b: 'El flujo completo de automatización', c: 'Tipo de usuario', d: 'Error del sistema' }, respuestaCorrecta: 'b', claseRelacionada: 18 },
  { id: 19, enunciado: '¿Qué herramienta ayuda a analizar datos de Excel con IA?', opciones: { a: 'Instagram', b: 'ChatGPT con archivo adjunto (Plus)', c: 'TikTok', d: 'Canva' }, respuestaCorrecta: 'b', claseRelacionada: 9 },
  { id: 20, enunciado: '¿Para qué sirve Gemini de Google?', opciones: { a: 'Editar fotos', b: 'Alternativa a ChatGPT integrada con G Suite', c: 'Hacer videos', d: 'Comprar online' }, respuestaCorrecta: 'b', claseRelacionada: 10 },
  { id: 21, enunciado: 'En automatización, ¿qué es un "Router"?', opciones: { a: 'Dispositivo de red', b: 'Módulo que divide el flujo en múltiples caminos', c: 'Tipo de imagen', d: 'Herramienta de traducción' }, respuestaCorrecta: 'b', claseRelacionada: 18 },
  { id: 22, enunciado: '¿Qué mínimo de asistencia requiere el certificado ITC?', opciones: { a: '50%', b: '60%', c: '75%', d: '90%' }, respuestaCorrecta: 'c', claseRelacionada: 22 },
  { id: 23, enunciado: '¿Qué es un "agente de IA"?', opciones: { a: 'Vendedor humano', b: 'Sistema que ejecuta tareas de forma autónoma', c: 'Tipo de contraseña', d: 'Herramienta de diseño' }, respuestaCorrecta: 'b', claseRelacionada: 20 },
  { id: 24, enunciado: '¿Qué hace la función "Magic Write" de Canva?', opciones: { a: 'Elimina errores', b: 'Genera texto con IA', c: 'Borra fondos', d: 'Crea videos' }, respuestaCorrecta: 'b', claseRelacionada: 6 },
  { id: 25, enunciado: '¿Qué herramienta sirve para crear subtítulos automáticos?', opciones: { a: 'Word', b: 'CapCut con IA', c: 'Paint', d: 'Excel' }, respuestaCorrecta: 'b', claseRelacionada: 8 },
  { id: 26, enunciado: 'El módulo "Aggregator" en Make...', opciones: { a: 'Elimina datos', b: 'Une múltiples flujos en uno solo', c: 'Envía SMS', d: 'Traduce texto' }, respuestaCorrecta: 'b', claseRelacionada: 18 },
  { id: 27, enunciado: '¿Qué significa "SOP" en el contexto de productividad?', opciones: { a: 'Software de pago', b: 'Procedimiento operativo estándar', c: 'Sistema online privado', d: 'Servidor de operaciones' }, respuestaCorrecta: 'b', claseRelacionada: 12 },
  { id: 28, enunciado: 'Para conectar WhatsApp con Make, se puede usar...', opciones: { a: 'Google Maps', b: 'UltraMsg o WhatsApp Business API', c: 'Adobe Photoshop', d: 'Microsoft Office' }, respuestaCorrecta: 'b', claseRelacionada: 19 },
  { id: 29, enunciado: '¿Cuál es la diferencia principal entre Zapier y Make?', opciones: { a: 'Zapier es más barato siempre', b: 'Make tiene interfaz visual en red, más flexible para flujos complejos', c: 'No hay diferencia', d: 'Make es solo para grandes empresas' }, respuestaCorrecta: 'b', claseRelacionada: 16 },
  { id: 30, enunciado: 'El Proyecto Final del curso debe incluir...', opciones: { a: 'Solo un video', b: 'Al menos 3 módulos en Make + uso de IA en alguna etapa', c: 'Un sitio web completo', d: 'Solo texto escrito' }, respuestaCorrecta: 'b', claseRelacionada: 21 },
]

// Logros
export const logrosDemo: Logro[] = [
  { id: '1', titulo: 'Primera clase completada', descripcion: 'Completaste tu primera clase del curso', icono: '🔥', desbloqueado: true, fechaDesbloqueo: new Date('2026-02-15') },
  { id: '2', titulo: '5 clases seguidas', descripcion: 'Completaste 5 clases sin faltar', icono: '⚡', desbloqueado: true, fechaDesbloqueo: new Date('2026-03-15') },
  { id: '3', titulo: 'Terminé el módulo de Diseño', descripcion: 'Completaste todas las clases de Diseño con IA', icono: '🎨', desbloqueado: false },
  { id: '4', titulo: 'Domino el Prompt Engineering', descripcion: 'Obtuviste más del 90% en ejercicios de prompts', icono: '🤖', desbloqueado: true, fechaDesbloqueo: new Date('2026-03-01') },
  { id: '5', titulo: 'Maestro de Make', descripcion: 'Completaste todas las clases de automatización', icono: '⚙️', desbloqueado: false },
  { id: '6', titulo: 'Aprobé el examen', descripcion: 'Aprobaste el examen final con más del 70%', icono: '🏆', desbloqueado: false },
]

// Prácticas del curso (una por clase, opcionales)
export interface Practica {
  id: number
  numero: number
  titulo: string
  claseRelacionada: number
  htmlPath: string
  duracion: number
  fase: number
  categoria: string
  categoriaLabel: string
}

export const practicasDemo: Practica[] = [
  // Fase 1
  { id: 1,  numero: 1,  titulo: 'Identificá la IA en tu día a día',         claseRelacionada: 1,  htmlPath: '/practicas/Practica_01_IA_En_Tu_Vida.html',          duracion: 30, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 2,  numero: 2,  titulo: 'Escribí tus primeros prompts',              claseRelacionada: 2,  htmlPath: '/practicas/Practica_02_Prompt_Engineering.html',     duracion: 45, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 3,  numero: 3,  titulo: 'Simulación de atención al cliente con IA',  claseRelacionada: 3,  htmlPath: '/practicas/Practica_03_Ventas_Atencion.html',        duracion: 40, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'Aplicación Comercial' },
  { id: 4,  numero: 4,  titulo: 'Creá textos de venta con IA',               claseRelacionada: 4,  htmlPath: '/practicas/Practica_04_Copywriting.html',            duracion: 40, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 5,  numero: 5,  titulo: 'Generá imágenes para tu negocio',           claseRelacionada: 5,  htmlPath: '/practicas/Practica_05_Diseno_Visual.html',          duracion: 45, fase: 1, categoria: 'diseno-ia',      categoriaLabel: 'Diseño con IA' },
  { id: 6,  numero: 6,  titulo: 'Diseñá un flyer en Canva con IA',           claseRelacionada: 6,  htmlPath: '/practicas/Practica_06_Canva.html',                  duracion: 50, fase: 1, categoria: 'diseno-ia',      categoriaLabel: 'Diseño con IA' },
  { id: 7,  numero: 7,  titulo: 'Editá un video corto con CapCut',           claseRelacionada: 7,  htmlPath: '/practicas/Practica_07_Video_Marketing.html',        duracion: 50, fase: 1, categoria: 'diseno-ia',      categoriaLabel: 'Diseño con IA' },
  { id: 8,  numero: 8,  titulo: 'Armá tu sistema de productividad',          claseRelacionada: 8,  htmlPath: '/practicas/Practica_08_Productividad.html',          duracion: 35, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 9,  numero: 9,  titulo: 'Analizá tu mercado con IA',                 claseRelacionada: 9,  htmlPath: '/practicas/Practica_09_Analisis_Clientes.html',     duracion: 40, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 10, numero: 10, titulo: 'Creá un reporte de datos con IA',           claseRelacionada: 10, htmlPath: '/practicas/Practica_10_Datos_Excel.html',            duracion: 45, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 11, numero: 11, titulo: 'Configurá tu primer GPT personalizado',     claseRelacionada: 11, htmlPath: '/practicas/Practica_11_GPT_Personalizado.html',      duracion: 50, fase: 1, categoria: 'estrategia',     categoriaLabel: 'Estrategia' },
  { id: 12, numero: 12, titulo: 'Simulá un análisis financiero PyME',        claseRelacionada: 12, htmlPath: '/practicas/Practica_12_Finanzas.html',               duracion: 40, fase: 1, categoria: 'estrategia',     categoriaLabel: 'Estrategia' },
  { id: 13, numero: 13, titulo: 'Autoevaluación Fase 1',                     claseRelacionada: 13, htmlPath: '/practicas/Practica_13_Repaso_Fase1.html',           duracion: 30, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 14, numero: 14, titulo: 'Explorá un agente de IA en acción',         claseRelacionada: 14, htmlPath: '/practicas/Practica_14_Agentes_IA.html',             duracion: 35, fase: 1, categoria: 'ia-aplicada',    categoriaLabel: 'IA Aplicada' },
  { id: 15, numero: 15, titulo: 'Mini Proyecto I — Entrega guiada',          claseRelacionada: 15, htmlPath: '/practicas/Practica_15_Mini_Proyecto.html',          duracion: 60, fase: 1, categoria: 'proyectos',      categoriaLabel: 'Proyectos' },
  // Fase 2
  { id: 16, numero: 16, titulo: 'Tu primer escenario en Make',               claseRelacionada: 16, htmlPath: '/practicas/Practica_16_Intro_Automatizacion.html',   duracion: 45, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 17, numero: 17, titulo: 'Conectá dos apps reales en Make',           claseRelacionada: 17, htmlPath: '/practicas/Practica_17_Conexiones_Make.html',        duracion: 50, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 18, numero: 18, titulo: 'Consumí una API y procesá JSON',            claseRelacionada: 18, htmlPath: '/practicas/Practica_18_APIs_JSON.html',              duracion: 50, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 19, numero: 19, titulo: 'Automatizá un mensaje de WhatsApp',         claseRelacionada: 19, htmlPath: '/practicas/Practica_19_WhatsApp.html',               duracion: 55, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 20, numero: 20, titulo: 'Integrá ChatGPT dentro de Make',            claseRelacionada: 20, htmlPath: '/practicas/Practica_20_IA_Make.html',                duracion: 55, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 21, numero: 21, titulo: 'Manejá errores y filtros en tu flujo',      claseRelacionada: 21, htmlPath: '/practicas/Practica_21_Errores_Filtros.html',        duracion: 45, fase: 2, categoria: 'automatizacion',  categoriaLabel: 'Automatización' },
  { id: 22, numero: 22, titulo: 'Proyecto Final — Guía paso a paso',         claseRelacionada: 22, htmlPath: '/practicas/Practica_22_Proyecto_Final.html',         duracion: 90, fase: 2, categoria: 'proyectos',      categoriaLabel: 'Proyectos' },
]

// Función para obtener el color de la categoría
export function getCategoriaColor(categoria: string): string {
  const colores: Record<string, string> = {
    'ia-aplicada': 'bg-blue-500',
    'diseno-ia': 'bg-pink-500',
    'estrategia': 'bg-violet-500',
    'automatizacion': 'bg-purple-500',
    'proyectos': 'bg-emerald-500',
  }
  return colores[categoria] || 'bg-slate-500'
}

export function getCategoriaTextColor(categoria: string): string {
  const colores: Record<string, string> = {
    'ia-aplicada': 'text-blue-600',
    'diseno-ia': 'text-pink-600',
    'estrategia': 'text-violet-600',
    'automatizacion': 'text-purple-600',
    'proyectos': 'text-emerald-600',
  }
  return colores[categoria] || 'text-slate-600'
}

export function getCategoriaBgLight(categoria: string): string {
  const colores: Record<string, string> = {
    'ia-aplicada': 'bg-blue-50 text-blue-700 border-blue-200',
    'diseno-ia': 'bg-pink-50 text-pink-700 border-pink-200',
    'estrategia': 'bg-violet-50 text-violet-700 border-violet-200',
    'automatizacion': 'bg-purple-50 text-purple-700 border-purple-200',
    'proyectos': 'bg-emerald-50 text-emerald-700 border-emerald-200',
  }
  return colores[categoria] || 'bg-slate-50 text-slate-700 border-slate-200'
}
